blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ä¸€èˆ¬è®¨è®º
    url: https://github.com/ixiongdi/nav/discussions
    about: ç”¨äºä¸€èˆ¬é—®é¢˜ã€è®¨è®ºå’Œæƒ³æ³•äº¤æµ
  - name: ğŸ”’ å®‰å…¨æ¼æ´æŠ¥å‘Š
    url: mailto:security@example.com
    about: è¯·ç§ä¸‹æŠ¥å‘Šå®‰å…¨æ¼æ´ï¼ˆä¸è¦åˆ›å»ºå…¬å¼€Issueï¼‰